name: Publish docker packages on github
on:
  push:
    tags:
      - '*'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Publish docker packages
        run: ./modules/cli/Dockerfile/docker-build-push.sh $TAG
        shell: bash
        env:
          TAG: ${{github.ref}}